area1: "" {
  rectangle.shape: rectangle
  square.shape: square
  parallelogram.shape: parallelogram
  hexagon.shape: hexagon
  diamond.shape: diamond
}


area2: "" {
  package.shape: package
  step.shape: step
  stored_data.shape: stored_data
  oval.shape: oval
  circle.shape: circle
  document.shape: document
}

area3: "" {
  page.shape: page
  callout.shape: callout
  cloud.shape: cloud
  person.shape: person
  queue.shape: queue
  cylinder.shape: cylinder
}


area3 -- area1 -- area2