# uncomment next line to make the diagram even more beautiful
# direction: right

# level 1
Diagram {
  style.fill: "#ffcccc"
}

Diagram -- structure
Diagram -- behavior

# level 2
structure: Structure Diagram
behavior: Behavior Diagram

structure -- Profile Diagram
structure -- Class Diagram
structure -- Composite Structure Diagram
structure -- Component Diagram
structure -- Deployment Diagram
structure -- Object Diagram
structure -- Package Diagram

interaction: Interaction Diagram

behavior -- Activity Diagram
behavior -- interaction
behavior -- Use Case Diagram
behavior -- State Machine Diagram
behavior -- New Diagram

interaction -- Sequence Diagram
interaction -- Communication Diagram
interaction -- Interaction Overview Diagram
interaction -- Timing Diagram
